theme:
  main: "&0&0&c&0&c&8"
  secondary: "&0&0&9&6&C&8"

permission-prefix: "nrcore."
no-permission: " &cYou are missing the permission: "
wrong-usage: "&cIncorrect Usage: "

spawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0.0
  pitch: 0.0

teleport:
  sound: ENTITY_ENDERMAN_TELEPORT
  delay: 5

# World Guard configs
world-guard:
  block-state-change: true

messaging:
  sent: "&3To &b%player% &f%msg%"
  from: "&3From &b%player% &f%msg%"

# SQL DB ONLY USE FOR DEVELOPERS USING API
sql:
  # Enable usage of a sql Database
  sql-enabled: false
  # The Url of the database, NOT INCLUDING HTTP:// or :// or HTTPS://
  sql-url: ""
  # SUPERUSER name of the database
  sql-user: ""
  # The SUPERUSER password for the database
  sql-password: ""
