theme:
  main: "&0&0&c&0&c&8"
  secondary: "&0&0&9&6&C&8"

no-permission: " &cYou are missing the permission: "

spawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0.0
  pitch: 0.0

teleport:
  sound: ENTITY_ENDERMAN_TELEPORT
  delay: 5

help:
  - "I love helping people"
  - "Helping is &cwhat &fI do&l!"

world-guard:
  block-state-change: true